version: '3'
services:
  frontend:
    container_name: ui
    build:
      context: . # relative to docker-compose command running directory (.) means this folder
      dockerfile: dockers/angular/Dockerfile # specify path to Dockerfile it starts on current folder application
    image: angular
    ports:
      # user can access that 4000 port
      - '4000:4200'
    stdin_open: true # stdin_open and tty: keep open the terminal after building container
    tty: true
