version: '3'
# can extends service that you need
# remember you can use the same service name
# As backend service is not api service
services:

  backend:
    extends:
      file: backend/docker-compose-backend.yml
      # container name api
      service: backend

  database:
    extends:
      file: backend/docker-compose-database.yml
      service: database

  frontend:
    extends:
      file: docker-compose-angular.yml
      service: frontend

# have to set it again because it can't see
volumes: # for storing value on container (can call service in backend part)
  # like volumes:
  #      - information-database:/var/lib/mysql
  information-database: # define volume name
    driver: local # use only current pc
